import 'package:flutter/material.dart';

final ValueNotifier<Locale> localeNotifier = ValueNotifier(const Locale('en'));

class AppLocalization {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {}, // English is fallback, no need to duplicate keys
    'ta': {
      'Settings': 'அமைப்புகள்',
      'Personal Information': 'தனிப்பட்ட தகவல்',
      'App Lock PIN': 'ஆப் லாக் பின்',
      'Push Notifications': 'அறிவிப்புகள்',
      'Dark Mode': 'இருண்ட முறை',
      'Language': 'மொழி',
      'Help Center': 'உதவி மையம்',
      'Terms & Policies': 'விதிமுறைகள் & கொள்கைகள்',
      'Log Out': 'வெளியேறு',
      'Select Language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'Sales Dashboard': 'விற்பனை டாஷ்போர்டு',
      'Total Sales': 'மொத்த விற்பனை',
      'Orders': 'ஆர்டர்கள்',
      'Customers': 'வாடிக்கையாளர்கள்',
      'Invoices': 'இன்வாய்ஸ்கள்',
      'Quick Actions': 'விரைவான செயல்கள்',
      'Report': 'அறிக்கை',
      'Sales Overview': 'விற்பனை மேலோட்டம்',
      'Order Status': 'ஆர்டர் நிலை',
      'Total Purchase': 'மொத்த கொள்முதல்',
      'Pending Approvals': 'நிலுவையில் உள்ள ஒப்புதல்கள்',
      'Total PR': 'மொத்த PR',
      'Total PO': 'மொத்த PO',
      'Create PR': 'PR உருவாக்கு',
      'Approvals': 'ஒப்புதல்கள்',
      'Sign in': 'உள்நுழைய',
      'Manage your customers, sales & business anywhere.': 'உங்கள் வாடிக்கையாளர்கள், விற்பனை மற்றும் வணிகத்தை எங்கும் நிர்வகிக்கவும்.',
      'Enter User Mail': 'மின்னஞ்சலை உள்ளிடவும்',
      'Enter Mobile Number': 'மொபைல் எண்ணை உள்ளிடவும்',
      'Enter Whatsapp Number': 'வாட்ஸ்அப் எண்ணை உள்ளிடவும்',
      'Next': 'அடுத்தது',
      'or continue with': 'அல்லது இதனுடன் தொடரவும்',
      'Whatsapp': 'வாட்ஸ்அப்',
      'Via SMS': 'SMS மூலம்',
      'Via Mail': 'மின்னஞ்சல் மூலம்',
      'Don’t Have An Account? ': 'கணக்கு இல்லையா? ',
      'Sign Up': 'பதிவு செய்க',
      'By Continuing you agree to our': 'தொடர்வதன் மூலம் நீங்கள் எங்களின் விதிமுறைகளை ஏற்கிறீர்கள்',
      'Terms and Conditions': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'Verify with OTP': 'OTP மூலம் சரிபார்க்கவும்',
      'Waiting to automatically detect an OTP sent to': 'அனுப்பப்பட்ட OTP-ஐத் தானாகவே கண்டறிய காத்திருக்கிறது',
      'Wrong mail?': 'தவறான மின்னஞ்சலா?',
      'Wrong Number?': 'தவறான எண்ணா?',
      'Resend OTP': 'OTP-ஐ மீண்டும் அனுப்பு',
      'Verify': 'சரிபார்க்கவும்',
      'Please enter all 6 OTP digits': 'அனைத்து 6 OTP எண்களையும் உள்ளிடவும்',
      'OTP Resent Successfully': 'OTP வெற்றிகரமாக மீண்டும் அனுப்பப்பட்டது',
      'Enter OTP': 'OTP-ஐ உள்ளிடவும்',
      'Network error, please try again': 'பிணைய பிழை, மீண்டும் முயற்சிக்கவும்',
      'Global Erp Dashboard': 'குளோபல் Erp டாஷ்போர்டு',
      'Global Erp': 'குளோபல் Erp',
      'GLOBAL ERP Dashboard': 'குளோபல் Erp டாஷ்போர்டு',
      'GLOBAL ERP': 'குளோபல் Erp',
      'Analytics & Reports': 'பகுப்பாய்வு மற்றும் அறிக்கைகள்',
      'Workplace Dashboard': 'பணியிட டாஷ்போர்டு',
      'You have 3 unread messages': 'உங்களுக்கு 3 படிக்காத செய்திகள் உள்ளன',
      'Manage preferences and configuration': 'விருப்பத்தேர்வுகள் மற்றும் கட்டமைப்பை நிர்வகிக்கவும்',
      'Select an App to Manage': 'நிர்வகிக்க ஒரு பயன்பாட்டைத் தேர்ந்தெடுக்கவும்',
      'HRM': 'HRM',
      'CRM': 'CRM',
      'Inventory': 'சரக்கு',
      'Accounting': 'கணக்கியல்',
      'Sales': 'விற்பனை',
      'Ecommerce': 'ஈகாமர்ஸ்',
      'Warehouse': 'கிடங்கு',
      'Manufacturing': 'தயாரிப்பு',
      'Purchase': 'கொள்முதல்',
      'Dealer Mgmt': 'டீலர் மேலாண்மை',
      'Purchase Management': 'கொள்முதல் மேலாண்மை',
      'Menu': 'பட்டியல்',
      'Purchase Orders': 'கொள்முதல் ஆர்டர்கள்',
      'Reports': 'அறிக்கைகள்',
      'Analytics': 'பகுப்பாய்வு',
      'Quotation Details': 'ஏல விவரங்கள்',
      'Select this Supplier': 'இந்த வழங்குநரைத் தேர்ந்தெடுக்கவும்',
      'Export PDF': 'PDF ஏற்றுமதி',
      'Compare All': 'அனைத்தையும் ஒப்பிடு',
      'PRODUCT RATES': 'தயாரிப்பு விகிதங்கள்',
      'PRODUCT': 'தயாரிப்பு',
      'RATE': 'விகிதம்',
      'QTY': 'அளவு',
      'DIS %': 'தள்ளுபடி %',
      'GST %': 'ஜிஎஸ்டி %',
      'TOTAL': 'மொத்தம்',
      'Grand Total (incl. GST)': 'பெரிய மொத்தம் (ஜிஎஸ்டி உட்பட)',
      'SUPPLIER': 'வழங்குநர்',
      'DELIVERY': 'விநியோகம்',
      'VALID TILL': 'வரை செல்லுபடியாகும்',
      'RFQ REF': 'RFQ குறிப்பு',
      'Date': 'தேதி',
      'Debit Voucher': 'டெபிட் வவுச்சர்',
      'Entry': 'பதிவு',
      'Records': 'பதிவுகள்',
      'Search records...': 'பதிவுகளைத் தேடு...',
      'Debit Records': 'டெபிட் பதிவுகள்',
      'Total Entries': 'மொத்த பதிவுகள்',
      'Total Amount': 'மொத்த தொகை',
      'Delete Record': 'பதிவை நீக்கு',
      'Cancel': 'ரத்துசெய்',
      'Delete': 'நீக்கு',
      'Are you sure you want to delete this record?': 'இந்த பதிவை நீக்க விரும்புகிறீர்களா?',
      'Saved successfully!': 'வெற்றிகரமாக சேமிக்கப்பட்டது!',
      'Please enter all fields': 'அனைத்து புலங்களையும் நிரப்பவும்',
      'Sales Order': 'விற்பனை ஆர்டர்',
      'Sales Invoice': 'விற்பனை விலைப்பட்டியல்',
      'Proforma Invoice': 'புரோபார்மா விலைப்பட்டியல்',
      'Direct Invoice': 'நேரடி விலைப்பட்டியல்',
      'Delivery Challan': 'டெலிவரி சலான்',
      'Quick Actions': 'விரைவான செயல்கள்',
      'Monthly Revenue Trend': 'மாதாந்திர வருவாய் போக்கு',
    },
    'hi': {
      'Settings': 'सेटिंग्स',
      'Personal Information': 'व्यक्तिगत जानकारी',
      'App Lock PIN': 'ऐप लॉक पिन',
      'Push Notifications': 'अधिसूचनाएं',
      'Dark Mode': 'डार्क मोड',
      'Language': 'भाषा',
      'Help Center': 'सहायता केंद्र',
      'Terms & Policies': 'नियम और नीतियां',
      'Log Out': 'लॉग आउट',
      'Select Language': 'भाषा चुनें',
      'Sales Dashboard': 'बिक्री डैशबोर्ड',
      'Total Sales': 'कुल बिक्री',
      'Orders': 'आदेश',
      'Customers': 'ग्राहक',
      'Invoices': 'इनवॉइस',
      'Quick Actions': 'त्वरित कार्रवाई',
      'Report': 'रिपोर्ट',
      'Total Purchase': 'कुल खरीद',
      'Pending Approvals': 'लंबित अनुमोदन',
      'Sign in': 'साइन इन करें',
      'Next': 'अगला',
      'Verify': 'सत्यापित करें',
      'Global Erp Dashboard': 'ग्लोबल ईआरपी डैशबोर्ड',
      'Global Erp': 'ग्लोबल ईआरपी',
      'GLOBAL ERP Dashboard': 'ग्लोबल ईआरपी डैशबोर्ड',
      'GLOBAL ERP': 'ग्लोबल ईआरपी',
      'Quotation Details': 'कोटेशन विवरण',
      'Select this Supplier': 'इस विक्रेता को चुनें',
      'Export PDF': 'पीडीएफ निर्यात करें',
      'Compare All': 'सभी की तुलना करें',
      'PRODUCT RATES': 'उत्पाद दरें',
      'Grand Total (incl. GST)': 'कुल योग (जीएसटी सहित)',
      'SUPPLIER': 'आपूर्तिकर्ता',
      'Date': 'तारीख',
      'Debit Voucher': 'डेबिट वाउचर',
      'Entry': 'प्रविष्टि',
      'Records': 'रिकॉर्ड',
      'Sales Order': 'बिक्री आदेश',
      'Sales Invoice': 'बिक्री चालान',
      'Proforma Invoice': 'प्रोफार्मा चालान',
      'Direct Invoice': 'सीधा चालान',
      'Delivery Challan': 'डिलिवरी चालान',
      'Quick Actions': 'त्वरित कार्रवाई',
      'Monthly Revenue Trend': 'मासिक राजस्व रुझान',
    },
  };

  static String of(String text) {
    if (_localizedValues.containsKey(localeNotifier.value.languageCode)) {
      return _localizedValues[localeNotifier.value.languageCode]?[text] ?? text;
    }
    return text;
  }
}
